<?php
require_once("database.php");

class Tags extends Database
{
    public function resultset()
    {
        $posts = parent::resultset(); // TODO: Change the autogenerated stub

        if(is_array($posts) && count($posts))
        {
            foreach($posts as &$post)
            {
                $tags = [];

                $query = "SELECT t.name FROM blog_post_tags bt LEFT JOIN tags t ON bt.id = t.id WHERE bt.id = :blogId";
                parent::query($query);
                parent::bind(':blogId', $post['id']);
                $blogTags = parent::resultset();

                foreach($blogTags as $btag)
                {
                    array_push($tags, $btag['name']);
                }

                $post['tags'] = implode(', ', $tags);
            }
            return $posts;
        }
        else
        {
            return [];
        }
    }
}