<?php
/**
 * Created by PhpStorm.
 * User: session2
 * Date: 9/30/16
 * Time: 4:13 PM
 */
require_once("database.php");

class Tags extends Database{

    public function resultset()
    {

        $posts = parent::resultset(); //TODO: Change the autogenerated stub

        if (is_array($posts) && count($posts)){

            foreach ($posts as &$post) {

                $tags = [];

                $query = "SELECT t.name FROM blog_post_tags bpt LEFT JOIN tags t ON bpt.id = t.id WHERE bpt.id = :blogid";
                parent::query($query);
                parent::bind(':blogid', $post['id']);
                $blogTags = parent::resultset();

                foreach ($blogTags as $btag){

                    array_push($tags, $btag['name']);

                    }

                $post['tags'] = implode(', ', $tags);

            }

            return $posts;

        }else{

            return [];

        }

    }

}